name: CI/CD

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest #σε τι μηχάνημα τρέχει 
    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v2 #library
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - name: Download deps #download libraries 
        run: npm i


      - name: Run tests 
        run: npm run test

  cd: 
    runs-on: ubuntu-latest 
    needs: ci 
    if: github.ref == 'refs/heads/main' # add comment here 
    steps: 
      - name : Chekout repo 
        uses: actions/checkout@v2

      - name : Install Railway 
        run: npm i -g @railway/cli # The client for the railway 

      - name: Deploy railway 
        run: railway up --service 968e8961-7523-4ea4-b310-e79009104c92 #which app to run the service 
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
