name: CI/CD

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest #σε τι μηχάνημα τρέχει 
    steps: 
      - name: Checkout repo 
        uses: action/checkout@v2 #library
      
      - name: Setup node
        uses: action/setup-node@v3
        with:
          node-version: 16 

      - name: Download deps #download libraries 
        run: npm i


      - name: Run tests 
        run: npm run test

